name: CI test
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup Python"
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: "Build and remove the magent import"
      run: pip install -e .

    - name: "Run tests"
      run: |
        pytest tests/
